project:
  type: website
  output-dir: _site
  
website:
  title: "Ryan Dearing Portfolio"
  navbar:
    # logo: 
    # logo-href: 
    right:

      - icon: linkedin
        href: https://www.linkedin.com/in/ryan-dearing/
      - icon: github
        href: https://github.com/dearingdata
     
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
  page-footer:
    center: 
      - text: "About"
        href: about.qmd

  favicon: 
  twitter-card: true
  comments: false
  # google-analytics:
  # body-header:
  # body-footer:

format:
  html:
    theme: cosmo #darkly #pulse #skectchy #superhero 
    css: styles.css
  
